[package]
name = "ingestor"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.22"
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
bsread = {version = "0.4.0", features = ["async"],  path = "/Users/gobbo_a/dev/bsread_rust"}
env_logger = "0.10"
clap = "4.5.23"
serde_json = "1.0.151"
crossbeam-channel = "0.5.16"